language: node_js
node_js:
- 6
install: npm install
script:
- npm run build-common
- npm test
- npm run build
- npm run build-gh-pages
deploy:
  - provider: npm
    email: onap.sdc@gmail.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
      repo: onap-sdc/sdc-ui
  - provider: pages
    repo: onap-sdc/sdc-ui
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: .out
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: .out
    on:
      all_branches: true
      condition: $DEPLOY = 1
